#!/usr/bin/env bash

FLASHING_SUCCEEDED=0
TARGET_NOT_RESPONDING=1
U_BOOT_FAILED_ERR=2
FLASHING_TIMEOUT=3
FLASHED_SIZE_MISMATCH=4
DB_FILE_MISSING=6
MISSING_IMAGE_FILE=7
TARGET_NOT_FOUND=8
USAGE_ERROR=9